services:
  postgres:
    image: postgres:17
    container_name: prisma-with-next-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: